version: '3.1'

services:
    app:
        build: .
        environment:
            FLASK_APP: app
            FLASK_ENV: development
            SECRET_KEY: abc123
            MYSQL_HOST: db
        ports:
            - 5000:5000
        volumes:
            - .:/app
    db:
        image: mysql
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: todo
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: app
            MYSQL_PASSWORD: password
        ports:
             - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
             - 8080:8080
