openapi: '3.1.0'
info:
  title: Todo List API
  version: '0.1'
servers:
  - url: http://localhost:5000
paths:
  /health:
    get:
      responses:
        200:
          description: Service is healthy
          content:
            text/html:
              schema:
                type: string
                example: OK