openapi: '3.0.3'
info:
  title: Todo List API
  version: '0.1'
servers:
  - url: http://localhost:5000
paths:
  /health:
    get:
      description: health status
      summary: health status
      responses:
        200:
          description: Service is healthy
          content:
            text/html:
              schema:
                type: string
                example: OK
      tags:
        - health
  /lists/:
    get:
      description: Get all lists
      summary: Get all lists
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listCollection"
      tags:
        - lists
    post:
      description: Create a new list
      summary: Create list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/listName"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
      tags:
        - lists
  /lists/{listId}:
    get:
      description: Get a specific list by listId
      summary: Get a specific list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
      tags:
        - lists
    patch:
      description: Update an existing list
      summary: Edit list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/listName"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
      tags:
        - lists
    delete:
      description: Delete a list
      summary: Delete a list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      responses:
        204:
          description: OK (list deleted)
      tags:
        - lists
components:
  parameters:
    listIdParam:
      name: listId
      description: A UUID identifier for the list record
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/listId"
  schemas:
    listCollection:
      type: array
      items:
        $ref: "#/components/schemas/list"
    list:
      type: object
      properties:
        listId:
          $ref: "#/components/schemas/listId"
        listName:
          $ref: "#/components/schemas/listName"
        createdAt:
          $ref: "#/components/schemas/createdAt"
        updatedAt:
          $ref: "#/components/schemas/updatedAt"
    listName:
      type: string
      description: The title of the list
      example: pikachu
      minimum: 0
      maximum: 60
    listId:
      type: string
      description: A UUID identifier for the list record
      example: fedc4195-c648-4cce-aed3-8295e4daf9de
    createdAt:
      type: string
      description: Timestamp in ISO 8601 format for when the record was created.
      example: 2024-05-14T01:12:39
    updatedAt:
      type: string
      description: Timestamp in ISO 8601 format for when the record was last updated.
      example: 2024-05-14T01:12:39
tags:
  - name: health
    description: Health check
  - name: lists
    description: Todo lists.  A [todo] list is a collection of items.