openapi: '3.0.3'
info:
  title: Todo List API
  version: '0.1'
servers:
  - url: http://localhost:5000
  - url: https://api.todolist.tryandbry.com
paths:
  /health:
    get:
      description: health status
      summary: health status
      responses:
        200:
          description: Service is healthy
          content:
            text/html:
              schema:
                type: string
                example: OK
      tags:
        - health
  /lists/:
    get:
      description: Get all lists
      summary: Get all lists
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listCollection"
      tags:
        - lists
    post:
      description: Create a new list
      summary: Create list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/listName"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
      tags:
        - lists
  /lists/{listId}:
    get:
      description: Get a specific list by listId
      summary: Get a specific list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
      tags:
        - lists
    patch:
      description: Update an existing list
      summary: Edit list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/listName"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/list"
      tags:
        - lists
    delete:
      description: Delete a list
      summary: Delete a list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      responses:
        204:
          description: OK (list deleted)
      tags:
        - lists
  /items/:
    get:
      description: Get all items
      summary: Get all items
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/itemCollection"
      tags:
        - items
  /items/{itemId}:
    get:
      description: Get a specific item by itemId
      summary: Get a specific item
      parameters:
        - $ref: "#/components/parameters/itemIdParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
      tags:
        - items
    patch:
      description: Update an existing item
      summary: Edit item
      parameters:
        - $ref: "#/components/parameters/itemIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/itemName"
                completed:
                  $ref: "#/components/schemas/itemCompleted"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
      tags:
        - items
    delete:
      description: Delete a item
      summary: Delete a item
      parameters:
        - $ref: "#/components/parameters/itemIdParam"
      responses:
        204:
          description: OK (item deleted)
      tags:
        - items
  /lists/{listId}/items:
    get:
      description: Get a list's items
      summary: Get items by list
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/itemCollection"
      tags:
        - items
    post:
      description: Create a new item associated with a list
      summary: Create item
      parameters:
        - $ref: "#/components/parameters/listIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/itemName"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"
      tags:
        - items
components:
  parameters:
    listIdParam:
      name: listId
      description: A UUID identifier for the list record
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/listId"
    itemIdParam:
      name: itemId
      description: A UUID identifier for the item record
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/itemId"
  schemas:
    listCollection:
      type: array
      items:
        $ref: "#/components/schemas/list"
    list:
      type: object
      properties:
        listId:
          $ref: "#/components/schemas/listId"
        name:
          $ref: "#/components/schemas/listName"
        createdAt:
          $ref: "#/components/schemas/createdAt"
        updatedAt:
          $ref: "#/components/schemas/updatedAt"
    listName:
      type: string
      description: The title of the list
      example: pikachu
      minimum: 0
      maximum: 60
    listId:
      type: string
      description: A UUID identifier for the list record
      example: fedc4195-c648-4cce-aed3-8295e4daf9de
    itemCollection:
      type: array
      items:
        $ref: "#/components/schemas/item"
    item:
      type: object
      properties:
        itemId:
          $ref: "#/components/schemas/itemId"
        name:
          $ref: "#/components/schemas/itemName"
        completed:
          $ref: "#/components/schemas/itemCompleted"
        list:
          type: object
          properties:
            listId:
              $ref: "#/components/schemas/listId"
        createdAt:
          $ref: "#/components/schemas/createdAt"
        updatedAt:
          $ref: "#/components/schemas/updatedAt"
    itemName:
      type: string
      description: The title of the item
      example: milk
      minimum: 0
      maximum: 60
    itemId:
      type: string
      description: A UUID identifier for the item record
      example: fedc4195-c648-4cce-aed3-8295e4daf9de
    itemCompleted:
      type: boolean
      description: Whether or not the [todo] item was completed
      example: true
    createdAt:
      type: string
      description: Timestamp in ISO 8601 format for when the record was created.
      example: 2024-05-14T01:12:39
    updatedAt:
      type: string
      description: Timestamp in ISO 8601 format for when the record was last updated.
      example: 2024-05-14T01:12:39
tags:
  - name: health
    description: Health check
  - name: lists
    description: Todo lists.  A list is a collection of items.
  - name: items
    description: Todo items.  A task on a list.