openapi: '3.1.0'
info:
  title: Todo List API
  version: '0.1'
servers:
  - url: http://localhost:5000
paths:
  /health:
    get:
      responses:
        200:
          description: Service is healthy
          content:
            text/html:
              schema:
                type: string
                example: OK
  /lists:
    get:
      responses:
        200:
          description: Get all lists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/listCollection"
components:
  schemas:
    listCollection:
      type: array
      items:
        $ref: "#/components/schemas/list"
    list:
      type: object
      properties:
        listId:
          type: string
          description: A UUID identifier for the list record
          example: fedc4195-c648-4cce-aed3-8295e4daf9de
        name:
          type: string
          description: The title of the list
          example: pikachu
        createdAt:
          type: string
          description: Timestamp in ISO 8601 format for when the list record was created.
          example: 2024-05-14T01:12:39
        updatedAt:
          type: string
          description: Timestamp in ISO 8601 format for when the list record was last updated.
          example: 2024-05-14T01:12:39